### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/Downloads'

### ISSUE THREAD

**Issue by gbdrbob** [kageurufu/steamdeck-tricks#1]
Hi,

When attempting to follow your EA App guide protontricks crashed when trying to install the wine-mono and wine-gecko dependencies:

```
$ flatpak run com.github.Matoking.protontricks -c 'wine msiexec /i "~/.cache/wine/wine-mono-7.2.0-x86.msi"' $STEAM_APP_ID
Traceback (most recent call last):
  File "/app/bin/protontricks", line 8, in <module>
    sys.exit(cli())
  File "/app/lib/python3.9/site-packages/protontricks/cli/main.py", line 30, in cli
    main(args)
  File "/app/lib/python3.9/site-packages/protontricks/cli/util.py", line 148, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/app/lib/python3.9/site-packages/protontricks/cli/main.py", line 341, in main
    returncode = run_command(
  File "/app/lib/python3.9/site-packages/protontricks/util.py", line 396, in run_command
    process = _start_process(
  File "/app/lib/python3.9/site-packages/protontricks/util.py", line 224, in _start_process
    process = Popen(args=args, **kwargs)
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/Downloads'
```

This is because by default the permissions on the protontricks flatpak don't give it full access to the user's home directory. I fixed the error by granting access with this command:

`flatpak --user override --filesystem=home com.github.Matoking.protontricks`

I was then able to follow  the rest of the guide without issue. It might be a good idea to update the guide with that command.

all the best,

drbob

**Comment by FearTheGrackle** [comment]
Thanks this fixed the install for me.  However, even launched and signed in when I try to download a game it just says calculating size and then that disappears and the games never download

**Comment by gbdrbob** [comment]
What version of Proton are you using with EA Play? I've had success with Proton-GE7-24, installed into Steam using [ProtonUP-QT](https://davidotek.github.io/protonup-qt/) (it's available as a flatpak in the discover store)

**Comment by FearTheGrackle** [comment]
Turns out I was using regular proton-7, I had chosen experimental but it wasn't installed yet (the other issue on this repo talks about this).  Still had same issue after installing experimental though.  I reimaged deck last night so nice and clean now, and got experimental installed.  I'll try your GE7-24 advice, and run through the guide again today.  I'm also now running without an SD card installed (really didn't need it anyway, the 512GB was fine for me), wondering if that might have been part of issue.
